# Site settings
title: Den Williams
email: work@denwilliams.net
url: http://denwilliams.net
description: "Technology, photography, and other things I find interesting."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#0277bd' # http://materializecss.com/color.html light blue
  links: '#ffab40'

# Footer settings
footer: Den Williams

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/den_williams
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/denwilliams
  - title: github
    url: https://github.com/denwilliams

links:
  resume: http://resume.denwilliams.net
  blog: http://blog.denwilliams.net
  flickr: https://www.flickr.com/photos/denwilliams/
  500px: https://500px.com/denwilliams

# Build settings
markdown: kramdown
permalink: pretty
